config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'reviews/index'
  root to: "rooms#index"
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:new, :create] do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image

  validates :name,presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users
  has_many :reviews

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  

  has_many :room_users
  has_many :reviews
  has_many :rooms, through: :room_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @room = Room.find(params[:room_id])
    @reviews = @room.reviews.includes(:user)
  end

  def new
    @review = Review.new
  end

  def create
    @room = Room.find(params[:room_id])
    @review = @room.reviews.new(review_params)
    if @review.save
      redirect_to room_reviews_path(@room)
    else
      @reviews = @room.reviews.includes(:user)
      render :index
    end
  end

  private

  def review_params
    params.require(:review).permit(:name, :group, :proceeds, :comment, :image).merge(user_id: current_user.id)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    current_user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LookingBack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_main_page.html.erb
<div class="chat-header">
<div class="left-header">
    <div class="header-title">
     <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <a href="#">ログアウト</a>
    </div>
  </div>
</div>

<% if @reviews.exists?  %>
<div class="reviews">
  <% @reviews.each do |review| %>
     <div class="review-name">
      <%= review.name %>
     </div>
     <div class='item-img-content'>
      <%= image_tag review.image , class: "item-img" %>

    <% end%>
<% end%>
</div>

<div class="form">
  <%= link_to(new_room_review_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <% end %>
</div>

app/views/reviews/_side_bar.html.erb
<div class="side-bar-header">
<div class="header-name">
    <%= link_to current_user.name, edit_user_password_path(current_user) %>
  </div>
  <div class="create-room">
    <%= link_to "グループを作成する", new_room_path %>
  </div>
</div>

<div class="rooms">
<% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, room_reviews_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/reviews/index.html.erb
<div class="wrapper">
  <div class = "side-bar">
  <%= render "side_bar" %>
  </div>
  <div class = "chat">
  <%= render "main_page" %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="contents">
   <div class="container">
      <h1 class="sub-title">売場投稿</h1>
         <%= form_with model: @review, url: room_reviews_path, local: true do |f| %>
         <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
         <div class="form-wrap">
            <div class="form-group">
               <div class="form_text_wrap">
                  <label class="form-text">タイトル</label>
                     <%= f.text_field :name, class:"work-name"%>
               </div>
            </div>
            <div class="form-group">
               <div class="form_text_wrap">
                  <label class="form-text">グループ</label>
                    <%= f.text_field :group, class:"work-rule" %>
               </div>
            </div>
            <div class="form-group">
                <div class="form_text_wrap">
                  <label class="form-text">　売上　</label>
                    <%= f.text_field :proceeds, class:"work-rule" %>
               </div>
            </div>

            <div class="form-group">
                <div class="form_text_wrap">
                  <label class="form-text">コメント</label>
                    <%= f.text_area :comment, class:"work-rule" %>
               </div>
            </div>

              <div class="form-submit">
                 <div class="actions">
                   <%= f.submit '保存', class:"submit-btn" %>
                   <%= link_to '戻る', room_reviews_path, class:"submit-btn" %>
                 </div>
              </div>
              
           </div>
        <% end %>
    </div>
</div>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "reviews/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規グループ</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :グループ名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">共有するユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>